/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPRODGENEPDFBERNSTEINEFFI
#define ROOPRODGENEPDFBERNSTEINEFFI

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooListProxy.h" 
#include "RooAbsPdf.h"
#include "RooAbsCategory.h"
#include "TMath.h"

typedef double fptype; 
 
class RooProdGenePdfBernsteinEffi : public RooAbsPdf {
public:
  RooProdGenePdfBernsteinEffi() {} ; 
  RooProdGenePdfBernsteinEffi(const char *name, const char *title,
	      RooAbsReal& x,
	      RooAbsReal& y,
	      RooAbsReal& z,
	      const RooArgList& coefList1,
	      const RooArgList& coefList2,
	      int maxDegree1, 
	      int maxDegree2, 
	      int maxDegree3
	      );
  RooProdGenePdfBernsteinEffi(const RooProdGenePdfBernsteinEffi& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooProdGenePdfBernsteinEffi(*this,newname); }
  inline virtual ~RooProdGenePdfBernsteinEffi() { }

  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
protected:

  RooRealProxy _x ;
  RooRealProxy _y ;
  RooRealProxy _z ;
  RooListProxy _coefList1 ;
  RooListProxy _coefList2 ;
  Int_t _maxDegree1 ;
  Int_t _maxDegree2 ;
  Int_t _maxDegree3 ;
  Int_t _maxDegreeV ;
  Int_t _numParamsE ;

  const static int NormInteg = 11 ;
  double Norm[NormInteg];

  Double_t evaluate() const ;

private:
  fptype device_bernsteinkn_func(fptype x, fptype enne, fptype kappa) const;
  fptype device_coeffbinomial(fptype enne, fptype kappa) const;
  fptype device_EffiBernsteinkn_intgBin( fptype xLeft, fptype xRight, fptype enne, fptype kappa) const;
  ClassDef(RooProdGenePdfBernsteinEffi,1) // Your description goes here...
};
 
#endif
